### ISSUE TITLE
IllegalArgumentExceptions thrown

### ISSUE THREAD

**Issue by mast76** [HubitatCommunity/CoCoHue#4]
I get a lot of these errors in the log (5 per sec).

java.lang.IllegalArgumentException: No json  exists for response on line 167 (parseStates)

java.lang.IllegalArgumentException: Text must not be null or empty on line 167 (parseStates)

**Comment by RMoRobert** [comment]
Thanks for the report! I will need more information to figure out what is going on. What app or driver is this coming from? My best guess it the Bridge driver, and in this case, what's happening is that the Bridge--or something responding--is returning unexpected data. Enabling debug logging for the Bridge device may show you what happens just before this and provide more context. Seeing five of these at one time is "normal" (if there is an error), as there are five distinct sets of data the Bridge driver parses when a Bridge refresh/poll is performed, each doing a sanity check on the data. It should not be five per *second* constantly unless you have a polling interval of 1 second, which the app/driver does not allow you to select.

**Comment by mast76** [comment]
I had to modify line 167 to 
`def json;
   try {
       json = resp?.json
   } catch (Exception e) {
       //ignored
   }
   if (json == null) {`
Only then was I able to see what was causing the trouble.
It seems to be an HTTP 408 (timeout). Which happens very often.

**Comment by mast76** [comment]
I fixed the timeout issue by changing it from 15 to 30 in line 75.

**Comment by RMoRobert** [comment]
Thanks! I'm made some changes in v3.1 (just released) that should eliminate the mysterious error and replace it with a warning (by the app, not thrown by the platform anymore) if it happens. You may wish to keep your timeout modification if this is a frequent problem on your network.
