### ISSUE TITLE
Add support for Friends of Hue Light Switches

### ISSUE THREAD

**Issue by DerekSeaman** [HubitatCommunity/CoCoHue#5]
I have a Friends of Hue light switch (RunLessWire Click), which the Hue hub recognizes and it works fine. However, I don't see a way to expose those switches to Hubitat via CoCo. Can switch support be added?

**Comment by RMoRobert** [comment]
I have discussed the desire to add this support in the future in the Hubitat Community forum thread, which I recommended over using GitHub for discussion of the app/drivers. I have plans to implement this at some point. Thanks for the request!
